//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPIP.Net_ConvertToDatabase.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_addresstemp
    {
        public long autoid { get; set; }
        public Nullable<double> ip1 { get; set; }
        public Nullable<double> ip2 { get; set; }
        public string ip3 { get; set; }
        public string ip4 { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string provinces { get; set; }
        public string district { get; set; }
        public string address { get; set; }
    }
}
